[package]
name = "day19"
version = "0.1.0"
edition = "2021"

[dependencies]
aochelpers = "0.7.1"
dashmap = "6.1.0"
rayon = "1.10.0"
regex = "1.11.1"

[dependencies.code-timing-macros]
version = "0.0.5"
features = ["release"]

