[package]
name = "day18"
version = "0.1.0"
edition = "2021"

[dependencies]
aochelpers = "0.7.1"
pathfinding = "4.12.0"
rayon = "1.10.0"

[dependencies.code-timing-macros]
version = "0.0.5"
features = ["release"]

