[package]
name = "day5"
version = "0.1.0"
edition = "2021"

[dependencies]
aochelpers = "0.7.1"
nom = "7.1.3"
nom-supreme = "0.8.0"
rayon = "1.10.0"

[dependencies.code-timing-macros]
version = "0.0.5"
features = ["release"]
