[package]
name = "day25"
version = "0.1.0"
edition = "2021"

[dependencies]
aochelpers = "0.7.1"
either = "1.13.0"
itertools = "0.13.0"
rayon = "1.10.0"

[dependencies.code-timing-macros]
version = "0.0.5"
features = ["release"]

